spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/demo;DB_CLOSE_DELAY=-1
    username: demo
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  mail:
    host: mail.localhost
    port: 25
    username: system@localhost
    password: "some password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secretKey: "some-key"
  tokenValidityInMilliseconds: 86400000
  tokenValidityInMillisecondsForRememberMe:  2592000000

emails:
  from-user: info@devcomanda.com
  activation-base-url: http://127.0.0.1:8080